### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by pyrsmk** [ldd/better-package-json#14]
Hi,

I'm really excited about this extension but unfortunately it does not work on my environment, nothing is appended on my dependencies/devDependecies lines. Maybe I missed something?

OS : Linux Elementary 5.1.6
VSCode : 1.47.3

**Comment by ldd** [comment]
This is possible due to the fact that `safeMode` is `true` by default.

Have you tried turning it off? I think I need to write a better README. 

Thanks for using my extension!

**Comment by pyrsmk** [comment]
It does not seem to work either.

**Comment by ldd** [comment]
possible reason: you don't have  a `npm-package-lock.json` file (maybe because you are using an old version of npm?)

try `touch npm-package-lock.json`

**Comment by pyrsmk** [comment]
You're right, it comes from that. Because I have a `yarn.lock` instead :D 

I think you should support both, then.

**Comment by ldd** [comment]
I also usually typically use `yarn.lock`. I am sorry, I meant to say that a lock from either `npm` or `yarn` was needed.

Anyways, I'll try to get a VM with your OS and see if there is any other possible issue. I'll also try to think of other ways the extension could be failing.

=/

**Comment by a-sane** [comment]
I have the same problem

OS : macOS 10.14.6
VSCode : 1.47.3

**Comment by ldd** [comment]
Hang on tight guys! I'm super busy this week, but I'll take another fresh look at it this weekend.

**Comment by Nekonyx** [comment]
> Hang on tight guys! I'm super busy this week, but I'll take another fresh look at it this weekend.

Still busy?

**Comment by ldd** [comment]
wow. This is totally on me for not following up.
Thanks for reminding me. I'll actually take a look now.

**Comment by ldd** [comment]
https://github.com/ldd/better-package-json/blob/e88d074c19c2d04c521ffba044a35ed34d6f3068/src/helpers/updatePackages.ts#L49

It's `package-lock.json` not `npm-package-lock.json`

**Comment by ldd** [comment]
well, while noticing that, I can also say that there are no error notifications anywhere.

The extension can still silently fail if:
- you are not in a project and you have no `package.json` open (there should be a notification that it couldn't find such file)
- there is no node_modules folder

**Comment by pyrsmk** [comment]
I'm glad that this subject is finally handled! I would be happy to be able to use this extension in my team :)

**Comment by dhorkin** [comment]
I seem to be having this issue. I tried turning off safe mode. Is there a way to get a debug log?
